//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWithSubscribers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_Networks
    {
        public string Серийный_номер { get; set; }
        public string Наименование { get; set; }
        public Nullable<double> Количество_портов_ { get; set; }
        public string Стандарт_передачи_данных_ { get; set; }
        public Nullable<double> Частота { get; set; }
        public string Интерфейсы { get; set; }
        public string Скорость_передачи_данных { get; set; }
        public string Место_расположения { get; set; }
    }
}
