//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWithSubscribers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public string F1 { get; set; }
        public string C20_August { get; set; }
        public string C21_August { get; set; }
        public string C22_August { get; set; }
        public string C23_August { get; set; }
        public string C24_August { get; set; }
        public string C25_August { get; set; }
        public string C26_August { get; set; }
        public string C27_August { get; set; }
        public string C28_August { get; set; }
        public string C29_August { get; set; }
        public string C30_August { get; set; }
        public string C31_August { get; set; }
        public string C1_September { get; set; }
        public string C2_September { get; set; }
        public string C3_September { get; set; }
        public string C4_September { get; set; }
        public string C5_September { get; set; }
        public string C6_September { get; set; }
        public string C7_September { get; set; }
    }
}
