//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWithSubscribers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Nullable<System.DateTime> Дата_платежа { get; set; }
        public Nullable<double> Сумма_платежа { get; set; }
        public Nullable<double> Баланс_абонента { get; set; }
        public Nullable<System.DateTime> Дата_баланса { get; set; }
        public Nullable<double> Задолженность { get; set; }
        public string Номер_абонента { get; set; }
    }
}
