//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWithSubscribers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub
    {
        public string Номер_абонента { get; set; }
        public string ФИО { get; set; }
        public string Пол { get; set; }
        public string Дата_рождения { get; set; }
        public string Номер_телефона { get; set; }
        public string Электронная_почта { get; set; }
        public string Адрес_прописки { get; set; }
        public string Адрес_проживания { get; set; }
        public string Серия_и_номер_паспорта { get; set; }
        public string Код_подразделения { get; set; }
        public string Кем_выдан { get; set; }
        public string Дата_выдачи_паспорта { get; set; }
        public string Номер_договора { get; set; }
        public Nullable<System.DateTime> Дата_заключения_договора { get; set; }
        public string Тип_договора { get; set; }
        public string Причина_расторжения_договора { get; set; }
        public Nullable<double> Лицевой_счет { get; set; }
        public string Услуги { get; set; }
        public string Услуги1 { get; set; }
        public string Услуги2 { get; set; }
        public Nullable<System.DateTime> Дата_расторжения_договора { get; set; }
        public string F22 { get; set; }
        public string Серийный_номер_оборудования_ { get; set; }
    }
}
