//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWithSubscribers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тарифы2_
    {
        public string Услуга { get; set; }
        public string Название_тарифа { get; set; }
        public string Условия { get; set; }
        public Nullable<double> Стоимость__руб_мес { get; set; }
    }
}
