//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatusControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Highway
    {
        public string Серийный_номер { get; set; }
        public string Название { get; set; }
        public Nullable<double> C_Частота { get; set; }
        public string C_Коэффициент_затухания { get; set; }
        public string C_Технология_передачи_данных { get; set; }
        public string C_Расположение { get; set; }
        public string F7 { get; set; }
        public string F8 { get; set; }
        public string F9 { get; set; }
        public string F10 { get; set; }
        public string F11 { get; set; }
    }
}
